{
 "title": "AWS Direct Connect",
 "description": "Visualize AWS Direct Connect metrics",
 "tags": [
  "monitoringartist",
  "cloudwatch"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   {
    "name": "agg",
    "label": "Aggregation",
    "query": "1s,5s,10s,30s,1m,5m,15m,1h,6h,1d,7d,30d"
   },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "ConnectionId",
    "label": "ConnectionId",
    "query": {}
   },
   {
    "name": "VirtualInterfaceId",
    "label": "VirtualInterfaceId",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "ConnectionState/ConnectionEncryptionState",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "ConnectionId": "$ConnectionId" },
     "metricName": "ConnectionState",
     "namespace": "AWS/DX",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Minimum"
    },
    {
     "dimensions": { "ConnectionId": "$ConnectionId" },
     "metricName": "ConnectionEncryptionState",
     "namespace": "AWS/DX",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Minimum"
    }
   ]
  },
  {
   "title": "ConnectionBpsEgress/ConnectionBpsIngress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "dimensions": { "ConnectionId": "$ConnectionId" },
     "metricName": "ConnectionBpsEgress",
     "namespace": "AWS/DX",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ConnectionId": "$ConnectionId", "VirtualInterfaceId": "$VirtualInterfaceId" },
     "expression": "m1*-1",
     "id": "e1",
     "label": "ConnectionBpsIngress",
     "metricEditorMode": 1,
     "metricName": "VirtualInterfaceBpsIngress",
     "namespace": "AWS/DX",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ConnectionPpsEgress/ConnectionPpsIngress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "dimensions": { "ConnectionId": "$ConnectionId" },
     "metricName": "ConnectionPpsEgress",
     "namespace": "AWS/DX",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ConnectionId": "$ConnectionId", "VirtualInterfaceId": "$VirtualInterfaceId" },
     "expression": "m1*-1",
     "id": "e1",
     "label": "VirtualInterfacePpsIngress",
     "metricEditorMode": 1,
     "metricName": "VirtualInterfacePpsIngress",
     "namespace": "AWS/DX",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "VirtualInterfaceBpsEgress/VirtualInterfaceBpsIngress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "dimensions": { "ConnectionId": "$ConnectionId", "VirtualInterfaceId": "$VirtualInterfaceId" },
     "metricName": "VirtualInterfaceBpsEgress",
     "namespace": "AWS/DX",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ConnectionId": "$ConnectionId", "VirtualInterfaceId": "$VirtualInterfaceId" },
     "expression": "m1*-1",
     "id": "e1",
     "label": "VirtualInterfaceBpsIngress",
     "metricEditorMode": 1,
     "metricName": "VirtualInterfaceBpsIngress",
     "namespace": "AWS/DX",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "VirtualInterfacePpsEgress/VirtualInterfacePpsIngress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "dimensions": { "ConnectionId": "$ConnectionId", "VirtualInterfaceId": "$VirtualInterfaceId" },
     "metricName": "VirtualInterfacePpsEgress",
     "namespace": "AWS/DX",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ConnectionId": "$ConnectionId", "VirtualInterfaceId": "$VirtualInterfaceId" },
     "expression": "m1*-1",
     "id": "e1",
     "label": "VirtualInterfacePpsIngress",
     "metricEditorMode": 1,
     "metricName": "VirtualInterfacePpsIngress",
     "namespace": "AWS/DX",
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 35 },
   "options": {
    "content": "<a target=\"_blank\" href=\"http://www.monitoringartist.com\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/directconnect/latest/UserGuide/monitoring-cloudwatch.html\">AWS CloudWatch Direct Connect documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/dashboards/17978\">Installed from Grafana.com dashboards</a>"
   }
  }
 ]
}