{
 "title": "AWS Network Firewall",
 "description": "Visualize AWS VPN metrics",
 "tags": [
  "monitoringartist",
  "cloudwatch"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "firewallname",
    "label": "FirewallName",
    "query": "dimension_values($region, AWS/NetworkFirewall, Packets, FirewallName)"
   },
   {
    "name": "availabilityzone",
    "label": "AvailabilityZone",
    "query": "dimension_values($region, AWS/NetworkFirewall, Packets, AvailabilityZone)"
   },
   {
    "name": "engine",
    "label": "Engine",
    "query": "dimension_values($region, AWS/NetworkFirewall, Packets, Engine)"
   }
  ]
 },
 "panels": [
  {
   "title": "Packets: Dropped / Passed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "AvailabilityZone": "$availabilityzone", "Engine": "$engine", "FirewallName": "$firewallname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "PassedPackets",
     "namespace": "AWS/NetworkFirewall",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "AvailabilityZone": "$availabilityzone", "Engine": "$engine", "FirewallName": "$firewallname" },
     "metricName": "DroppedPackets",
     "namespace": "AWS/NetworkFirewall",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Received Packets Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "AvailabilityZone": "$availabilityzone", "Engine": "$engine", "FirewallName": "$firewallname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReceivedPacketCount",
     "namespace": "AWS/NetworkFirewall",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Packets (CustomAction)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "AvailabilityZone": "$availabilityzone", "Engine": "$engine", "FirewallName": "$firewallname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Packets",
     "namespace": "AWS/NetworkFirewall",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "TransitGateway": "$transitgateway" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BytesOut",
     "namespace": "AWS/TransitGateway",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "<a style=\"float: right\" href=\"http://www.monitoringartist.com\" target=\"_blank\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a>\n<a style=\"float: left\"  target=\"_blank\" href=\"http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/monitoring-cloudwatch-vpn.html\">AWS CloudWatch VPN documentation</a><br/>\n<a style=\"float: left\"  target=\"_blank\" href=\"https://grafana.com/dashboards/2969\">Installed from Grafana.com dashboards</a>\n<div style=\"clear:both; width:100%;height:0;font-size:0;\"></div>"
   }
  }
 ]
}