{
 "title": "AWS Kinesis Firehose",
 "description": "Visualize AWS Kinesis Data Firehose metrics",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   {
    "name": "agg",
    "label": "Aggregation",
    "query": "1s,5s,10s,30s,1m,5m,15m,1h,6h,1d,7d,30d"
   },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "deliverystreamname",
    "label": "DeliveryStreamName",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Data Ingestion Through Direct PUT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "IncomingRecords/IncomingBytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "DeliveryStreamName": "$deliverystreamname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "IncomingRecords",
     "namespace": "AWS/Firehose",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "DeliveryStreamName": "$deliverystreamname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "IncomingBytes",
     "namespace": "AWS/Firehose",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "RecordsPerSecondLimit/ThrottledRecords",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "DeliveryStreamName": "$deliverystreamname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "RecordsPerSecondLimit",
     "namespace": "AWS/Firehose",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "DeliveryStreamName": "$deliverystreamname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "ThrottledRecords",
     "namespace": "AWS/Firehose",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Delivery to Splunk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "DeliveryToSplunk.Records/DeliveryToSplunk.Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "DeliveryStreamName": "$deliverystreamname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "DeliveryToSplunk.Records",
     "namespace": "AWS/Firehose",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "DeliveryStreamName": "$deliverystreamname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "DeliveryToSplunk.Bytes",
     "namespace": "AWS/Firehose",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "DeliveryToSplunk.Success/DeliveryToSplunk.DataFreshness",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "DeliveryStreamName": "$deliverystreamname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "DeliveryToSplunk.Success",
     "namespace": "AWS/Firehose",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "SampleCount"
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "DeliveryStreamName": "$deliverystreamname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "DeliveryToSplunk.DataFreshness",
     "namespace": "AWS/Firehose",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 },
   "options": {
    "content": "<a href=\"http://www.monitoringartist.com\" target=\"_blank\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/streams/latest/dev/monitoring-with-cloudwatch.html\">AWS CloudWatch Kinesis documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/dashboards/20144\">Installed from Grafana.com dashboards</a>"
   },
   "targets": [
    {}
   ]
  }
 ]
}