{
 "title": "AWS Storage Gateway",
 "description": "Visualize AWS Storage Gateway metrics",
 "tags": [
  "monitoringartist",
  "cloudwatch"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   {
    "name": "agg",
    "label": "Aggregation",
    "query": "1s,5s,10s,30s,1m,5m,15m,1h,6h,1d,7d,30d"
   },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "gatewayname",
    "label": "GatewayName",
    "query": "dimension_values($region,AWS/StorageGateway,UserCpuPercent,GatewayName)"
   },
   {
    "name": "gatewayid",
    "label": "GatewayId",
    "query": "dimension_values($region,AWS/StorageGateway,CacheHitPercent,GatewayId,{\"GatewayName\":\"$gatewayname\"})"
   },
   {
    "name": "volumeid",
    "label": "VolumeId",
    "query": "dimension_values($region,AWS/StorageGateway,WorkingStorageFree,VolumeId,{\"GatewayName\":\"$gatewayname\",\"GatewayId\":\"$gatewayid\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "UserCpuPercent/IoWaitPercent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "UserCpuPercent",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "IoWaitPercent",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CacheHitPercent/CacheUsed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayId": "$gatewayid", "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CacheHitPercent",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayId": "$gatewayid", "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CacheUsed",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "UploadBufferPercentUsed/UploadBufferUsed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "UploadBufferPercentUsed",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "UploadBufferUsed",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MemTotalBytes/MemUsedBytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "MemTotalBytes",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "MemUsedBytes",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CloudBytesUploaded/CloudBytesDownloaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayId": "$gatewayid", "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CloudBytesUploaded",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayId": "$gatewayid", "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CloudBytesDownloaded",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "ReadBytes/ReadTime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayId": "$gatewayid", "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReadBytes",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayId": "$gatewayid", "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReadTime",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "WriteBytes/WriteTime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayId": "$gatewayid", "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "WriteBytes",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayId": "$gatewayid", "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "WriteTime",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "IndexEvictions/IndexFetches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayId": "$gatewayid", "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "IndexEvictions",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayId": "$gatewayid", "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "IndexFetches",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "SmbV1Sessions/SmbV2Sessions/SmbV3Sessions/NfsSessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SmbV1Sessions",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SmbV2Sessions",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SmbV3Sessions",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NfsSessions",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "WorkingStorageFree/WorkingStorageUsed/WorkingStoragePercentUsed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "WorkingStorageFree",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "WorkingStorageUsed",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "WorkingStoragePercentUsed",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "AvailabilityNotifications/QueuedWrites",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "AvailabilityNotifications",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "GatewayName": "$gatewayname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "QueuedWrites",
     "namespace": "AWS/StorageGateway",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 77 },
   "options": {
    "content": "<a target=\"_blank\" href=\"http://www.monitoringartist.com\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/storagegateway/latest/userguide/Main_monitoring-gateways-common.html\">AWS CloudWatch Storage Gateway documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/dashboards/13040\">Installed from Grafana.com dashboards</a>\n"
   }
  }
 ]
}