{
 "title": "AWS Transit Gateway",
 "description": "Visualize AWS Transit Gateway metrics",
 "tags": [
  "monitoringartist",
  "cloudwatch"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "transitgateway",
    "label": "TransitGateway",
    "query": "dimension_values($region, AWS/TransitGateway, BytesIn, TransitGateway)"
   }
  ]
 },
 "panels": [
  {
   "title": "Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "TransitGateway": "$transitgateway" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BytesIn",
     "namespace": "AWS/TransitGateway",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "TransitGateway": "$transitgateway" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BytesOut",
     "namespace": "AWS/TransitGateway",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "TransitGateway": "$transitgateway" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "PacketsIn",
     "namespace": "AWS/TransitGateway",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "TransitGateway": "$transitgateway" },
     "metricName": "PacketsOut",
     "namespace": "AWS/TransitGateway",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Packet Drop Count: No Route / Blackhole",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "TransitGateway": "$transitgateway" },
     "metricName": "PacketDropCountNoRoute",
     "namespace": "AWS/TransitGateway",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "TransitGateway": "$transitgateway" },
     "metricName": "PacketDropCountBlackhole",
     "namespace": "AWS/TransitGateway",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "<a style=\"float: right\" href=\"http://www.monitoringartist.com\" target=\"_blank\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a>\n<a style=\"float: left\"  target=\"_blank\" href=\"https://docs.aws.amazon.com/vpc/latest/tgw/transit-gateway-cloudwatch-metrics.html\">CloudWatch metrics for your transit gateways</a><br/>\n<div style=\"clear:both; width:100%;height:0;font-size:0;\"></div>"
   }
  }
 ]
}