{
 "title": "AWS Step Functions",
 "description": "Visualize AWS Step Functions metrics",
 "tags": [
  "cloudwatch",
  "monitoringartist"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   {
    "name": "agg",
    "label": "Aggregation",
    "query": "1s,5s,10s,30s,1m,5m,15m,1h,6h,1d,7d,30d"
   },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "stateMachineArn",
    "label": "StateMachineArn",
    "query": "dimension_values($region,AWS/States,ExecutionsFailed,StateMachineArn)"
   }
  ]
 },
 "panels": [
  {
   "title": "Executions Succeeded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "StateMachineArn": "$stateMachineArn" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ExecutionsSucceeded",
     "namespace": "AWS/States",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Execution Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "StateMachineArn": "$stateMachineArn" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ExecutionTime",
     "namespace": "AWS/States",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "StateMachineArn": "$stateMachineArn" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ExecutionTime",
     "namespace": "AWS/States",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Executions Started",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "StateMachineArn": "$stateMachineArn" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ExecutionsStarted",
     "namespace": "AWS/States",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Executions Failed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "StateMachineArn": "$stateMachineArn" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ExecutionsFailed",
     "namespace": "AWS/States",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Executions TimedOut",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "StateMachineArn": "$stateMachineArn" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ExecutionsTimedOut",
     "namespace": "AWS/States",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Executions Aborted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "StateMachineArn": "$stateMachineArn" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ExecutionsAborted",
     "namespace": "AWS/States",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Execution Throttled",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "StateMachineArn": "$stateMachineArn" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ExecutionThrottled",
     "namespace": "AWS/States",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 49 },
   "content": "<a target=\"_blank\" href=\"http://www.monitoringartist.com\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/step-functions/latest/dg/procedure-cw-metrics.html\">AWS CloudWatch Step Functions documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/dashboards/11099\">Installed from Grafana.com dashboards</a>\n"
  }
 ]
}